app_authentication/urls.py
from django.conf.urls import url
from .views import index
from .custom_auth import auth_login, auth_logout

urlpatterns = [
    url(r'^$', index, name='index'),
    
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),
]

app_mahasiswa/urls.py
from django.conf.urls import url
from .views import index
from .views_profile import *
from .views_riwayat import *
from .views_status import *
from .views_mahasiswa import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^profile', profile, name='profile'),
    url(r'^add_status', add_status, name='add_status'),
    url(r'^delete_status/(?P<id>\d+)/$', delete_status, name='delete_status'),
    
]

tugas2ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import app_mahasiswa.urls as app_mahasiswa
import app_authentication.urls as app_auth

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include(app_auth,namespace='app-auth')),
    url(r'^mahasiswa/', include(app_mahasiswa,namespace='app-mahasiswa')),
    url(r'^$', RedirectView.as_view(url="/login/", permanent = "true"), name='index')
]

app_authentication/models.py
from django.db import models

# Create your models here.

app_mahasiswa/models.py
from django.db import models

# Create your models here.
class Pengguna(models.Model):
    nama = models.CharField('nama', max_length=25, default='kosong')
    username = models.CharField('username', max_length=25, default='kosong', unique=True)
    npm = models.CharField('npm', max_length=25, primary_key=True, unique=True)
    profile_linkedin = models.CharField('profile_linkedin', max_length=25, default='kosong')
    foto_profil = models.URLField(default='https://hello-pet.com/assets/uploads/2016/03/aliando.jpg')
    email = models.CharField('email', max_length=25, default='kosong')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Status(models.Model):
    status = models.TextField()
    pengguna = models.ForeignKey(Pengguna, null = True)
    created_date = models.DateTimeField(auto_now_add=True)

class Keahlian(models.Model):
    keahlian = models.CharField('keahlian', max_length = 10)
    level = models.CharField('level', max_length = 15)
    pengguna = models.ForeignKey(Pengguna)

app_mahasiswa/forms.py
from django import forms

class Status_Form(forms.Form):
	status_attrs = {
		'type': 'text',
		'rows': 4,
		'class' : 'form-control',
		'placeholder': "What's happening?",
		'style': 'resize:none'
	}
	
	status = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=status_attrs))

app_authentication/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.

response = {'logged_in' : False}

def index(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('app-mahasiswa:index'))
    else:
        html = 'session/login.html'
        return render(request, html, response)

app_mahasiswa/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
# Create your views here.

response = {'author' : "Kelompok1"}

def index(request):
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect('/login/')

    return HttpResponseRedirect('/mahasiswa/profile')

app_authentication/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 9">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tugas_2.css' %}" />
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <title>
        {% block title %} Tugas 2 {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
    <!-- Your Header Here -->
    {% include "partials/header.html" %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    <hr>
    {% block footer %}
    <!-- Your Footer Here -->
    {% include "partials/footer.html" %}
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app_authentication/templates/partials/footer.html
<div id="myFooter">
    <br>
    <br>
    <br>
    <div class="footer-social">
        <a href="https://facebook.com" target="_blank" class="social-icons"><i class="fa fa-facebook"></i></a>
        <a href="https://plus.google.com/" target=_blank class="social-icons"><i class="fa fa-google-plus"></i></a>
        <a href="https://twitter.com/" class="social-icons" target="_blank"><i class="fa fa-twitter"></i></a>
    </div>
    <div class="container">
        <p class="footer-copyright"><b>© 2017 Kelompok 1 Cuuy</b></p>
    </div>
</div>

app_authentication/templates/partials/header.html
<nav class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">SocMed</a>
          </div>
          {% if login %}
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav nav-right pull-right">
              <li><a href="{% url 'app_authentication:auth_logout' %}" onclick="return confirm('Keluar?')">Logout</a></li>
            </ul>
          </div>
          {% endif %}
      </nav>

app_authentication/templates/session/login.html
{% extends "layout/base.html" %}
{% block content %}
<div class="row" style="background-image:https://simomot.com/wp-content/uploads/2014/02/3d-gif.gif">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1><b>Halaman Login</b> </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'app-auth:auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}

app_mahasiswa/templates/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 9">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="../../static/tugas_2.css">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <title>
        {% block title %} Tugas 2 PPW {{author}} {% endblock %}
    </title>
</head>
<body>
<header>
    <!-- Your Header Here -->
    {% include "partials/header.html" %}
</header>
<content>
    <div class="container">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible" role="alert" id="django-messages">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="margin-right: 15px;">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
        {% endfor %}

        {% block content %}
        <!-- Your Content Here -->
        {% endblock %}
    </div>
</content>
<footer>
    {% block footer %}
    <!-- Your Footer Here -->
    {% include "partials/footer.html" %}
    {% endblock %}
</footer>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

app_mahasiswa/templates/partials/footer.html
<div id="myFooter">
    <br>
    <br>
    <br>

    <div class="footer-social">
        <a href="https://facebook.com" target="_blank" class="social-icons"><i class="fa fa-facebook"></i></a>
        <a href="https://plus.google.com/" target=_blank class="social-icons"><i class="fa fa-google-plus"></i></a>
        <a href="https://twitter.com/" class="social-icons" target="_blank"><i class="fa fa-twitter"></i></a>
    </div>
    <div class="container">
        <p class="footer-copyright"><b>© 2017 Kelompok 1 Cuuy</b></p>
    </div>
</div>

app_mahasiswa/templates/partials/header.html
<nav class="navbar navbar-default navbar-static-top" style="color:">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="">SocMed</a>
          </div>

app_mahasiswa/templates/session/mahasiswaPage.html
{% extends "layout/base.html" %}
{% load static %}
{% block content %}
<!-- Content Here -->
<!-- tulisan nama, status terakhir, dll di sini-->

<h1 align="center", style="color:snow">Selamat Datang, {{ username }}!</h1>
<img src = "{{ foto_profil }}" alt = "profpic" width = "200px" height = "200px">
<div>
<button type="button">Hide Grades</button>
</div>
<h3>Jumlah Status : {{ total }} </h3>
<h3>
    <!-- if ada status, get status terakhir pake filter(-date) < cek status di tugas1
        kalo ga ada tinggal taro tidak ada status
     -->
</h3>

<!-- logout sementara -->
<a href="{% url 'app-auth:auth_logout' %}" class="btn btn-danger pull-right" onclick="return confirm('Keluar?')">Logout </a>
    
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#profile" aria-controls="home" role="tab" data-toggle="tab"> Profile </a>
        </li>
        <li role="presentation">
            <a href="#riwayat" aria-controls="settings" role="tab" data-toggle="tab"> Riwayat </a>
        </li>
        <li role="presentation">
            <a href="#status" aria-controls="settings" role="tab" data-toggle="tab"> Status </a>
        </li>
        <li role="presentation">
            <a href="#teman" aria-controls="settings" role="tab" data-toggle="tab"> Teman </a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="profile">
            {% include 'tables/profile.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="riwayat">
            {% include 'tables/riwayat.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="status">
            {% include 'tables/status.html' %}
        </div>
        <div role="tabpanel" class="tab-pane fade" id="teman">
            {% include 'tables/teman.html' %}
        </div>
    </div>
</div>
{% endblock %}

app_mahasiswa/templates/tables/profile.html
{% load staticfiles %}
{% load static %}

<div class="panel panel-default">
    <div class="panel-body">
        <table class="table">
            <p>Nama : {{ nama }} </p>
            <p>NPM : {{ npm }} </p>
            <p>Keahlian :
                {% if list_keahlian %}
                    {% for keahlian in list_keahlian %}
                        {{ keahlian.keahlian }} 
                    {% endfor %}
                {% else %}
                    kosong
                {% endif %}
                </p>
            <p>Email : {{ email }} </p>
            <p>Profile LinkedIn : {{ profile_linkedin }} </p>
        </table>
    </div>
</div>

app_mahasiswa/templates/tables/riwayat.html
{% load staticfiles %}
{% load static %}

<div class="panel panel-default">
	<div class="panel-heading">
		<table style="width: 97%;">
	     	<thead>
		       <tr>
		         <th>No</th>
		         <th>Mata Kuliah</th>
		         <th>Dosen Pengajar</th>
		         <th>Nilai</th>
		       </tr>
		     </thead>
				  {% for riwayat in riwayats %}
	       <tr>
						<td>{{ forloop.counter }}</td>
		         <td>{{ riwayat.kelas.nm_mk_cl.nm_mk }}</td>
		         <td>{{ riwayat.kelas.pengajar.0.nama }}</td>
		         <td>{{ riwayat.nilai }}</td>
	       </tr>
				 {% endfor %}
		</table>
   	</div>
</div>

app_mahasiswa/templates/tables/status.html
{% load staticfiles %}
{% load static %}
<div class="panel panel-info">
        <div class="panel-body">
            <section name="input-list" id="input-list">
                <div class="container" style="width:100%;">
                	<form id="form" method="POST" action="{% url 'app-mahasiswa:add_status' %}">
                        <h2>Update Status</h2>
                        {% csrf_token %}
                        {{ status_form }}
                        <br>
                        <input id="post-button" type="submit" class="btn btn-lg btn-block btn-info" value="Post">
                    </form>
                </div>
            </section>
            <section name="my-list" id="my-list">
                <div class="container" style="width:100%;">
                    <h2 class="my-list-title">Timeline</h2>
                    <div class="flex">
                    {% if status %}
                    	{% for data in status %}
                            <div class="flex-item status-flex">
                                <a href="/mahasiswa/delete_status/{{ data.id }}">
                                    <div class="delete-button" data-id={{data.id}}}>x</div>
                                </a>
                                <div class="postee">
                                    <img class="img depe" src = "https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png" width="50px">
                                    {{ data.pengguna.username }}
                                </div>
            				    <div class="isi-status">{{data.status}}</div>
            				    <div class="date-added" id="date-added">{{data.created_date}}</div>
                            </div>
                    	{% endfor %}
                    {% else %}
                    <div class="alert alert-danger text-center">
                        <strong>Oops!</strong> Tidak ada post di timeline.
                    </div>
                    {% endif %}
                  </div>
                </div>
            </section>
        </div>
    </div>
{% load static %}

app_mahasiswa/templates/tables/teman.html
{% load staticfiles %}
{% load static %}